CREATE TABLE 
IF NOT EXISTS
    users(
        userslogin VARCHAR(64) NOT NULL PRIMARY KEY,
        usersPassword VARCHAR(64) NOT NULL,
        usersRole VARCHAR(20) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    flower(
        flowerId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        flowerName VARCHAR(500) NOT NULL,
        flowerPicture VARCHAR(500),
        localisationId SMALLINT NOT NULL,
        familyId SMALLINT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    localisation(
        localisationId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        localisationName VARCHAR(50) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    family(
        familyId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        familyName VARCHAR(50) NOT NULL,
        familyDesc VARCHAR(500)
    );