CREATE TABLE 
IF NOT EXISTS
    users(
        userslogin VARCHAR(64) NOT NULL PRIMARY KEY,
        usersPassword VARCHAR(64)
    );

CREATE TABLE 
IF NOT EXISTS
    flower(
        flowerId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        flowerPicture VARCHAR(500),
        localisationId SMALLINT NOT NULL,
        categoryId SMALLINT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    localisation(
        localisationId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        localisationName VARCHAR(50)
    );

CREATE TABLE 
IF NOT EXISTS
    family(
        familyId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        familyName VARCHAR(50),
        familyDesc VARCHAR(500)
    );